[template]
cargo_generate_version = ">=0.9.0"
description = "A Microbit project template"

[hooks]
pre = ["cargo-generate/prehook.rhai"]

[placeholders.abs_layer]
type = "string"
prompt = "BSP or HAL?"
choices = ["BSP", "HAL"]
default = "BSP"
